"use client";
import { useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, Check, CheckCircle2, CircleUserRound, Clock3, Download, ExternalLink, FileText, Mail, MessageSquarePlus, Paperclip, Pencil, Plus, Printer, Sparkles, UserRound } from "lucide-react";
import type { CaseRecord } from "@/lib/domain";
import { categoryLabels, priorityLabels, statusLabels } from "@/lib/domain";
import { formatCurrency, formatDate } from "@/lib/format";
import { CategoryIcon } from "./category-icon";
import { FineDeviceVerification } from "./fine-device-verification";
import type { FineTechnicalAnalysis } from "@/lib/fines/types";

export function CaseDetail({initialCase,fineAnalysis=null}:{initialCase:CaseRecord;fineAnalysis?:FineTechnicalAnalysis|null}){
  const [item,setItem]=useState(initialCase); const [notice,setNotice]=useState(""); const [source,setSource]=useState<string|null>(null);
  const confirmField=(id:string)=>{setItem(v=>({...v,fields:v.fields.map(f=>f.id===id?{...f,confirmed:true,needsHumanReview:false}:f)}));setNotice("Campo confermato e registrato nell’audit demo.")};
  const updateStatus=()=>{setItem(v=>({...v,status:v.status==="COMPLETED"?"IN_PROGRESS":"COMPLETED"}));setNotice("Stato aggiornato nella sessione demo.")};
  return <div className="page"><div className="page-heading"><div><Link href="/pratiche" className="source-link" style={{display:"inline-flex",alignItems:"center",gap:5}}><ArrowLeft size={13}/> Tutte le pratiche</Link><div style={{display:"flex",alignItems:"center",gap:12,marginTop:8}}><span className="type-icon" style={{width:40,height:40}}><CategoryIcon category={item.category} size={19}/></span><div><div className="eyebrow">{item.code} · {categoryLabels[item.category]}</div><h1>{item.title}</h1></div></div></div><div style={{display:"flex",gap:8}}><button className="btn" onClick={()=>window.print()}><Printer size={15}/> Stampa</button><a className="btn btn-primary" href={`/api/cases/${item.id}/pdf`}><Download size={15}/> Genera PDF</a></div></div>
    {notice&&<div className="warning" role="status" style={{marginBottom:16,borderLeftColor:"var(--green)",background:"#eef9f5",color:"#17634f"}}><CheckCircle2 size={14} style={{display:"inline",marginRight:7}}/>{notice}</div>}
    <div className="detail-grid"><div className="detail-main">
      <section className="box"><div className="box-head"><h2>Sintesi operativa</h2><span className={`badge priority-${item.priority}`}>{priorityLabels[item.priority]}</span></div><p className="summary-text">{item.summary}</p><div className="meta-grid"><Meta label="Stato" value={statusLabels[item.status]}/><Meta label="Responsabile" value={item.assignee??"Non assegnata"}/><Meta label="Scadenza" value={formatDate(item.deadline,true)}/><Meta label="Importo" value={formatCurrency(item.amount)}/></div></section>
      {fineAnalysis&&<FineDeviceVerification analysis={fineAnalysis} caseCode={item.code}/>} 
      {(item.anomalyFlags.length>0||item.emails.some(e=>e.securityFlags.length>0))&&<section className="box"><div className="box-head"><h2>Anomalie e controlli</h2><AlertTriangle size={18} color="var(--orange)"/></div>{[...item.anomalyFlags,...item.emails.flatMap(e=>e.securityFlags)].map(flag=><div className="warning" key={flag}><strong>{anomalyLabel(flag)}</strong><br/>Richiede verifica umana; nessuna azione esterna è stata eseguita.</div>)}</section>}
      <section className="box"><div className="box-head"><h2>Dati estratti <span className="count">{item.fields.length}</span></h2><span className={item.confidence<.72?"confidence-low":""} style={{fontSize:12}}>Confidenza {Math.round(item.confidence*100)}%</span></div><div className="field-list">{item.fields.map(field=><div className="field" key={field.id}><div className="field-top"><div><div className="field-label">{field.label}</div><div className="field-value">{field.value==null?"Non presente":String(field.value)}</div></div>{field.confirmed?<span className="badge status-COMPLETED"><Check size={11}/> Confermato</span>:<button className="btn" style={{minHeight:28,padding:"0 8px"}} onClick={()=>confirmField(field.id)}>Conferma</button>}</div><button className="source-link" onClick={()=>setSource(field.sourceExcerpt)}><ExternalLink size={10} style={{display:"inline",marginRight:4}}/>Apri fonte · {field.sourceType.replaceAll("_"," ").toLowerCase()}</button></div>)}</div></section>
      <section className="box"><div className="box-head"><h2>Cronologia email <span className="count">{item.emails.length}</span></h2></div><div className="timeline">{item.emails.map(email=><div className="timeline-item" key={email.id}><div className="timeline-dot"><Mail size={13}/></div><div><div className="timeline-title">{email.subject}</div><div className="timeline-copy">Da {email.fromName} · {formatDate(email.receivedAt,true)}<br/>{email.preview}</div>{email.attachments.map(att=><div className="attachment" key={att.id}><Paperclip size={15}/><div><div className="attachment-name">{att.filename}</div><div className="small-muted">{att.readable?`${Math.round(att.size/1000)} KB · Analizzato`:"Allegato non leggibile"}</div></div></div>)}</div></div>)}</div></section>
      <section className="box"><div className="box-head"><h2>Bozza di risposta</h2><span className="badge status-NEEDS_REVIEW"><UserRound size={11}/> Approvazione richiesta</span></div><div className="draft">{item.draft??"Nessuna bozza disponibile. Generane una usando esclusivamente i dati confermati."}</div><button className="btn" style={{marginTop:12}} onClick={()=>setNotice("Bozza rigenerata in modalità simulata; nessuna email è stata inviata.")}><Sparkles size={14}/> {item.draft?"Rigenera bozza":"Crea bozza"}</button></section>
      <section className="box"><div className="box-head"><h2>Registro attività</h2></div><div className="timeline">{item.audit.map(event=><div className="timeline-item" key={event.id}><div className="timeline-dot"><Clock3 size={13}/></div><div><div className="timeline-title">{event.action.replaceAll("_"," ")}</div><div className="timeline-copy">{event.actor} · {formatDate(event.createdAt,true)}<br/>{event.detail}</div></div></div>)}</div></section>
    </div><aside className="detail-side">
      <section className="box"><div className="box-head"><h2>Azioni</h2></div><div className="action-stack"><button className="btn"><CircleUserRound size={15}/> Assegna responsabile</button><button className="btn"><Pencil size={15}/> Modifica dati</button><button className="btn"><Plus size={15}/> Aggiungi attività</button><button className="btn"><MessageSquarePlus size={15}/> Commento interno</button><button className="btn"><FileText size={15}/> Genera documento</button><button className="btn btn-primary" onClick={updateStatus}><CheckCircle2 size={15}/> {item.status==="COMPLETED"?"Riapri pratica":"Segna completata"}</button></div></section>
      <section className="box"><div className="box-head"><h2>Contesto</h2></div><Meta label={item.partyType==="SUPPLIER"?"Fornitore":"Cliente / ente"} value={item.party}/><div style={{height:14}}/><Meta label="Reparto" value={item.department}/><div style={{height:14}}/><Meta label="Categorie secondarie" value={item.secondaryCategories.length?item.secondaryCategories.map(c=>categoryLabels[c]).join(", "):"Nessuna"}/></section>
      <section className="box"><div className="box-head"><h2>Controllo umano</h2></div><p className="summary-text" style={{fontSize:12}}>L’app non invia email, non registra pagamenti e non modifica il gestionale. Ogni azione esterna richiede approvazione esplicita.</p></section>
    </aside></div>
    {source&&<div role="dialog" aria-modal="true" style={{position:"fixed",inset:0,background:"rgba(11,26,42,.5)",zIndex:50,display:"grid",placeItems:"center",padding:20}} onClick={()=>setSource(null)}><div className="box" style={{maxWidth:540,width:"100%"}} onClick={e=>e.stopPropagation()}><div className="box-head"><h2>Fonte del dato</h2><button className="btn" onClick={()=>setSource(null)}>Chiudi</button></div><p className="summary-text">“{source}”</p><div className="small-muted">Contenuto sintetico non affidabile, mostrato senza HTML attivo.</div></div></div>}
  </div>
}
function Meta({label,value}:{label:string;value:string}){return <div><div className="meta-label">{label}</div><div className="meta-value">{value}</div></div>}
function anomalyLabel(flag:string){return ({POSSIBLE_DUPLICATE:"Possibile fattura duplicata",MISSING_DUE_DATE:"Data di scadenza assente",PAYMENT_NOT_VERIFIED:"Pagamento dichiarato ma non verificato",LOW_CONFIDENCE:"Classificazione a bassa confidenza",MULTIPLE_INTENTS:"Email con più intenzioni",PROMPT_INJECTION_ATTEMPT:"Tentativo di prompt injection",SECURITY_REVIEW:"Contenuto potenzialmente malevolo",UNREADABLE_ATTACHMENT:"Allegato non leggibile",AMOUNT_MISMATCH:"Importi discordanti",MISSING_REQUIRED_DATA:"Dati obbligatori mancanti",MISSING_DOCUMENTS:"Documenti mancanti"} as Record<string,string>)[flag]??flag.replaceAll("_"," ")}
